let vim_path  = '~/dot-files/vim/'  " TODO assign dynamically 
set runtimepath+=~/dot-files/vim

set nocompatible

exec "source" . vim_path . "/vimrcs/basic.vim"
exec "source" . vim_path. "/vimrcs/extended.vim"
exec "source" . vim_path . "/vimrcs/plugins.vim"

