let vim_path  = $HOME."/dot-files/vim/"  " TODO assign dynamically 
set runtimepath+=vim_path

set nocompatible

exec "source" . vim_path . "/vimrcs/basic.vim"
exec "source" . vim_path. "/vimrcs/extended.vim"
exec "source" . vim_path . "/vimrcs/plugins.vim"

